# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20170204_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='owner',
            field=models.EmailField(max_length=254),
        ),
    ]
